# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#jekyll serve --host 0.0.0.0

keep_files: [files]


title: 'Elek L치szl칩 SJ'
email: eleklaszlosj@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Elek L치szl칩 SJ. Jezsuita. Szerzetes. Pap.
baseurl: "" #"/jekyll-vagrant-setup" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


date_format: "%Y. %b %-d."

#https://github.com/jekyll/minima/blob/master/_includes/social.html
twitter_username: borazslo
github_username:  borazslo
facebook_username: eleklaszlo
flickr_username: borazslo
instagram_username: borazslo
linkedin_username: laszloeleksj
pinterest_username: borazslo

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-archives


#https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#page-configuration
pagination:
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true
  per_page: 10
  trail: 
      before: 4
      after: 4
  permalink: '/oldal/:num/' # Pages are html files, linked jekyll extensionless permalink style.
  title: ' - :num. oldal'
  # locale: 'hu_HU' 
  sort_field: 'date'
  sort_reverse: true


excerpt_separator: "<!--break-->"


jekyll-archives:
  enabled:
    - tags
    - categories
  layout: archive
  permalinks:
#    year: '/:year/'
#    month: '/:year/:month/'
#    day: '/:year/:month/:day/'
    tag: '/cimke/:name/'
#    category: '/category/:name/'

include:
    - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - eleklaszloDump.sql
    - migrate.php
    - deploy.sh
    - migration_log.txt
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

