name: deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup SSH-Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
      
          
      - name: Build Dist Site 
        uses: ./.github/actions/build-dist-site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PWD: ${{ secrets.PWD }}
          CPANEL: ${{ secrets.CPANEL }}
                    
